<?php
// Pure helpers for cover-image uploads. NO DB or network I/O.

const UPLOAD_MAX_BYTES = 5 * 1024 * 1024; // 5 MB

// Allowed image types (from getimagesize) -> safe file extension.
function upload_allowed_types(): array {
    return [
        IMAGETYPE_JPEG => 'jpg',
        IMAGETYPE_PNG  => 'png',
        IMAGETYPE_WEBP => 'webp',
        IMAGETYPE_GIF  => 'gif',
    ];
}

// Validate a just-uploaded image by size and by sniffing the real bytes.
// Size is measured from the file on disk (never trust a caller-supplied size).
// Returns ['ext' => 'jpg', 'error' => null] on success,
// or ['ext' => null, 'error' => '<reason>'] on failure.
function validate_image_upload(string $tmpPath): array {
    $size = @filesize($tmpPath);
    if ($size === false || $size <= 0) {
        return ['ext' => null, 'error' => 'The file is empty.'];
    }
    if ($size > UPLOAD_MAX_BYTES) {
        return ['ext' => null, 'error' => 'Image must be 5 MB or smaller.'];
    }
    $info = @getimagesize($tmpPath);
    if ($info === false || !isset($info[2])) {
        return ['ext' => null, 'error' => 'That file is not a valid image.'];
    }
    $allowed = upload_allowed_types();
    if (!isset($allowed[$info[2]])) {
        return ['ext' => null, 'error' => 'Unsupported image type. Use JPEG, PNG, WebP, or GIF.'];
    }
    return ['ext' => $allowed[$info[2]], 'error' => null];
}

// Resolve the filesystem dir and public URL base for cover uploads.
// Default: <web_root>/uploads/covers served at /uploads/covers, where the
// web root is the parent of the API directory (public_html/api -> public_html).
// Override via config (upload_dir / upload_base_url) for differing layouts.
function uploads_paths(array $cfg, string $apiDir): array {
    $dir = (isset($cfg['upload_dir']) && is_string($cfg['upload_dir']) && $cfg['upload_dir'] !== '')
        ? rtrim($cfg['upload_dir'], "/\\")
        : dirname($apiDir) . '/uploads/covers';
    $base = (isset($cfg['upload_base_url']) && is_string($cfg['upload_base_url']) && $cfg['upload_base_url'] !== '')
        ? rtrim($cfg['upload_base_url'], '/')
        : '/uploads/covers';
    return ['dir' => $dir, 'base_url' => $base];
}

// .htaccess written into the uploads tree so a disguised script can never be
// executed. Uses access denial (works under mod_php and PHP-FPM alike) rather
// than php_flag, which 500s under FPM.
function upload_htaccess_contents(): string {
    return "# Auto-generated by RecipeBytes. Uploaded files are data, never executable.\n"
         . "<FilesMatch \"(?i)\\.(php|phtml|php3|php4|php5|php7|phar|cgi|pl|py|sh)$\">\n"
         . "  Require all denied\n"
         . "</FilesMatch>\n"
         . "Options -ExecCGI\n"
         . "RemoveHandler .php .phtml .phar\n";
}

// Create the covers dir (recursive) if missing and drop the hardening
// .htaccess at the uploads root (parent of covers) on first use.
function ensure_uploads_dir(string $dir): void {
    if (!is_dir($dir)) {
        @mkdir($dir, 0775, true);
    }
    $ht = dirname($dir) . '/.htaccess';
    if (!file_exists($ht)) {
        @file_put_contents($ht, upload_htaccess_contents());
    }
}
